Новиков Анатолий Викторович

# NumPy

## Задание 1

1.

In [123]:
import numpy as np

In [5]:
a = np.arange(12,24)

In [6]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [7]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [11]:
a.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [12]:
a.reshape(2,-1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
a.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a.reshape(4,-1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [15]:
a.reshape(-1,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [16]:
a.reshape(-1,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Можно

2.

In [17]:
b = np.random.randn(3,4)

In [18]:
b

array([[-0.63063593,  1.09133711,  0.98100694,  0.10319664],
       [-1.90933156,  0.87556091,  0.40130704, -0.72395155],
       [-0.78964621, -0.90901631, -1.9079068 ,  0.80206888]])

In [22]:
c = b.flatten()

In [23]:
c

array([-0.63063593,  1.09133711,  0.98100694,  0.10319664, -1.90933156,
        0.87556091,  0.40130704, -0.72395155, -0.78964621, -0.90901631,
       -1.9079068 ,  0.80206888])

In [24]:
c.size

12

In [25]:
b.size

12

3.

In [27]:
a = np.arange(20,0,-2)

In [28]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [29]:
a.shape

(10,)

In [40]:
b = np.arange(20,1,-2).reshape(1,-1)

In [41]:
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [42]:
b.shape

(1, 10)

Разница в "шейпе"

4.

In [46]:
a = np.zeros((2,2))

In [47]:
b = np.ones((3,2))

In [48]:
a

array([[0., 0.],
       [0., 0.]])

In [49]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
v = np.concatenate((a,b))

In [58]:
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
v.size

10

5.

In [60]:
a = np.arange(0,12)

In [61]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
A = a.reshape(4,3)

In [64]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
At = A.transpose()

In [66]:
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [67]:
B = np.dot(A, At)

In [68]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [69]:
B.shape

(4, 4)

Обратную к B матрицу вычислить получится, если ее определитель будет отличен от нуля

6.

In [70]:
np.random.seed(42)

In [73]:
a = np.random.randint(0,16,size=16)

In [74]:
a

array([ 3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3])

In [75]:
C = a.reshape(4,-1)

In [76]:
C

array([[ 3, 12, 14, 10],
       [ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3]])

In [79]:
D = 10*C + B

In [80]:
D

array([[ 35, 134, 163, 132],
       [ 84, 170, 126, 182],
       [113, 106, 209, 312],
       [132, 192, 252, 332]])

In [81]:
np.linalg.det(D)

21320000.000000034

In [84]:
np.linalg.matrix_rank(D)

4

In [101]:
D_inv = np.linalg.inv(D)

In [102]:
D_inv

array([[-0.0421257 , -0.04781989, -0.07423077,  0.11272233],
       [ 0.00713133,  0.01837899,  0.00807692, -0.02050094],
       [-0.00235084, -0.03018386, -0.02807692,  0.04386679],
       [ 0.01440901,  0.03129456,  0.04615385, -0.06324578]])

7.

In [103]:
D_inv[D_inv < 0.] = 0.

In [106]:
D_inv[D_inv != 0.] = 1.

In [107]:
D_inv

array([[0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 1., 0.]])

In [108]:
E = np.where(D_inv, B, C)

In [109]:
E

array([[  3,  12,  14,  32],
       [ 14,  50,  86,   6],
       [  9,   2,   6, 212],
       [ 32, 122, 212,   3]])

## Задание 2

In [110]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [111]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [112]:
a.shape

(5, 2)

In [115]:
mean_a = np.mean(a,0)

In [116]:
mean_a

array([2. , 8.4])

## Задание 3

In [118]:
a_centered = a - mean_a

In [119]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 4

In [122]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])

In [123]:
a_centered_sp

8.0

In [130]:
r = a_centered_sp/(a_centered.shape[0]-1)

In [131]:
r

2.0

## Задание 5

In [128]:
R = np.cov(a.T)

In [129]:
R

array([[1. , 2. ],
       [2. , 4.3]])

In [132]:
R[0,1] == r

True

# Pandas

## Задание 1

In [14]:
import pandas as pd

In [19]:
authors = pd.DataFrame({'author_id':[1,2,3],
                       'author_name':['Тургенев','Чехов','Островский']})

In [20]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [22]:
books = pd.DataFrame({'author_id':[1,1,1,2,2,3,3],
                       'book_title':['Отцы и дети','Рудин','Дворянское гнездо','Толстый и тонкий','Дама с собачкой','Гроза','Таланты и поклонники'],
                     'price':[450,300,350,500,450,370,290]})

In [23]:
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2

In [24]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'inner')

In [25]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

In [27]:
top5 = authors_price.nlargest(5,'price')

In [28]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 4

In [60]:
min_p = authors_price.groupby('author_id')['price'].min()

In [61]:
min_p

author_id
1    300
2    450
3    290
Name: price, dtype: int64

In [62]:
max_p = authors_price.groupby('author_id')['price'].max()

In [63]:
max_p

author_id
1    450
2    500
3    370
Name: price, dtype: int64

In [85]:
mean_p = authors_price.groupby('author_id')['price'].mean()

In [110]:
make_float = lambda x: "{:,.2f}".format(x)
mean_p = mean_p.apply(make_float)

In [111]:
authors_stat = pd.DataFrame({})

In [112]:
authors_stat['author_name'] = authors['author_name'].values

In [113]:
authors_stat['min_price'] = min_p.values

In [114]:
authors_stat['max_price'] = max_p.values

In [115]:
authors_stat['mean_price'] = mean_p.values

In [117]:
authors_stat

author_name  min_price  max_price mean_price
0    Тургенев        300        450     366.67
1       Чехов        450        500     475.00
2  Островский        290        370     330.00

## Задание 5

In [118]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [119]:
authors_price['cover'] = ['твердая','мягкая','мягкая','твердая','твердая','мягкая','мягкая']

In [120]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [121]:
pd.pivot_table?

In [130]:
import numpy as np

In [131]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],columns=['cover'], aggfunc=np.sum, fill_value=0)

In [132]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [136]:
pd.to_pickle(book_info,"book_info.pkl")

In [137]:
book_info2 = pd.read_pickle("book_info.pkl")

In [138]:
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950